version: 3
endpoint: http://localhost:8080
metadata_directory: metadata
admin_secret: mwj1IJwmIYIVA0ma2Pb15@ethio_education_graphq_secret_90
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
